"""The agent rule-file registry — the single source for tool-specific rules.

Each supported agent host gets a thin rule file derived from ``AGENTS.md`` by
prepending a short header. ``AGENTS.md`` is the universal, natively-read source
(D10/D11); these files are compatibility shims for hosts that read their own
format. The same transform is used at two times, so it can never drift:

  - build time: scripts/generate.py writes the repo's scaffold/ rule files;
  - run time:   `cwy init` derives them into a new project (D38/D39).

Adding a new tool is a one-line change: append a ``RuleFile`` to ``RULE_FILES``.
"""
from __future__ import annotations

from dataclasses import dataclass

_CURSOR_PREAMBLE = """\
# Causeway — Cursor Rules
# Generated from AGENTS.md. Do not edit this file directly — edit AGENTS.md.

"""

_COPILOT_PREAMBLE = """\
<!-- Causeway — GitHub Copilot Instructions -->
<!-- Generated from AGENTS.md. Do not edit this file directly — edit AGENTS.md. -->

"""


@dataclass(frozen=True)
class RuleFile:
    """A tool-specific agent rule file derived from AGENTS.md."""

    path: str       # path written into a project (relative), e.g. ".cursorrules"
    label: str      # human label, e.g. "Cursor"
    preamble: str   # header prepended to the AGENTS.md body


CURSOR = RuleFile(
    path=".cursorrules",
    label="Cursor",
    preamble=_CURSOR_PREAMBLE,
)
COPILOT = RuleFile(
    path=".github/copilot-instructions.md",
    label="GitHub Copilot",
    preamble=_COPILOT_PREAMBLE,
)

# The registry. Append a RuleFile here to support another agent host.
RULE_FILES: list[RuleFile] = [CURSOR, COPILOT]


def render(rule: RuleFile, agents_md: str) -> str:
    """Derive a tool rule file's full text from the AGENTS.md body."""
    return rule.preamble + agents_md
